
function layBack(){



    //ALL SPEEDS ARE DIVIDED BY 10


    //IT MEANS , OPPONENTS SPEEDS ARE DIVIDED BY 10

    //We check what opponents are there. WE DIVIDE THEIR SPEEDS BY 10.

    //THEN, WE CHECK ALL THE PLAYERS THAT ARE PRESENT (MEANING WE LOOP ON THE OPPONENTS ARRAY. IF ONE OF THE OPPONENTS HAS THE VALUE ON SCREEN TRUE)


    //CHECK THE ACTIVE OPPONENTS (IN A DIV)


    //THE DIV SIMPLY FLOATS BACK.





}